// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/backend/config"
	"github.com/Wei-Shaw/sub2api/backend/internal/repository"
	"github.com/Wei-Shaw/sub2api/backend/internal/repository/postgres"
	redis2 "github.com/Wei-Shaw/sub2api/backend/internal/repository/redis"
	scheduler2 "github.com/Wei-Shaw/sub2api/backend/internal/scheduler"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/account"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/admin"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/billing"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/health"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/limit"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/proxy"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/relay"
	"github.com/Wei-Shaw/sub2api/backend/internal/service/scheduler"
	"github.com/Wei-Shaw/sub2api/backend/pkg/database"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"golang.org/x/oauth2"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServices(cfg *config.Config, log *zap.Logger, db *database.DB, redisClient *redis.Client) (*Services, error) {
	gormDB := provideGormDB(db)
	adminRepository := postgres.NewAdminRepository(gormDB)
	adminService := provideAdminService(adminRepository, cfg, log)
	proxyConfigRepository := postgres.NewProxyConfigRepository(gormDB)
	proxyClientManager := provideProxyClientManager(proxyConfigRepository, cfg, log)
	proxyConfigService := provideProxyConfigService(proxyConfigRepository, proxyClientManager, cfg, log)
	codexAccountRepository := postgres.NewCodexAccountRepository(gormDB)
	oAuthStateRepository := redis2.NewOAuthStateRepository(redisClient)
	oauth2Config := provideOAuth2Config(cfg)
	client := provideDefaultHTTPClient()
	codexAccountService := provideCodexAccountService(codexAccountRepository, oAuthStateRepository, oauth2Config, client, proxyClientManager, cfg, log)
	pricingService := providePricingService(log)
	costCalculator := billing.NewCostCalculator(pricingService, log)
	usageRepository := postgres.NewUsageRepository(gormDB)
	usageCollector := billing.NewUsageCollector(usageRepository, costCalculator, log)
	costLimiter := limit.NewCostLimiter(usageRepository, log)
	concurrencyTracker := provideConcurrencyTracker(redisClient, log)
	rateLimitRepository := redis2.NewRateLimitRepository(redisClient)
	rateLimiter := limit.NewRateLimiter(rateLimitRepository, log)
	sessionRepository := redis2.NewSessionRepository(redisClient)
	concurrencyRepository := provideAccountConcurrencyRepo(redisClient)
	healthRepository := redis2.NewHealthRepository(redisClient)
	selectionStrategy, err := provideSchedulerStrategy(cfg, concurrencyRepository)
	if err != nil {
		return nil, err
	}
	schedulerService := provideSchedulerService(codexAccountRepository, sessionRepository, concurrencyRepository, healthRepository, selectionStrategy, cfg, log)
	cleanupService := provideCleanupService(codexAccountRepository, log)
	healthChecker := provideHealthChecker(codexAccountRepository, healthRepository, log)
	codexRelayService := provideCodexRelayService(schedulerService, codexAccountService, usageCollector, proxyClientManager, cfg, log)
	apiKeyRepository := postgres.NewAPIKeyRepository(gormDB)
	services := &Services{
		AdminService:        adminService,
		ProxyClientManager:  proxyClientManager,
		ProxyConfigService:  proxyConfigService,
		CodexAccountService: codexAccountService,
		PricingService:      pricingService,
		CostCalculator:      costCalculator,
		UsageCollector:      usageCollector,
		CostLimiter:         costLimiter,
		ConcurrencyTracker:  concurrencyTracker,
		RateLimiter:         rateLimiter,
		SchedulerService:    schedulerService,
		CleanupService:      cleanupService,
		HealthChecker:       healthChecker,
		CodexRelayService:   codexRelayService,
		AdminRepo:           adminRepository,
		CodexAccountRepo:    codexAccountRepository,
		APIKeyRepo:          apiKeyRepository,
	}
	return services, nil
}

// wire.go:

type Services struct {
	AdminService        admin.AdminService
	ProxyClientManager  proxy.ProxyClientManager
	ProxyConfigService  proxy.ProxyConfigService
	CodexAccountService account.CodexAccountService
	PricingService      billing.PricingService
	CostCalculator      billing.CostCalculator
	UsageCollector      billing.UsageCollector
	CostLimiter         limit.CostLimiter
	ConcurrencyTracker  limit.ConcurrencyTracker
	RateLimiter         limit.RateLimiter
	SchedulerService    scheduler.SchedulerService
	CleanupService      scheduler.CleanupService
	HealthChecker       health.HealthChecker
	CodexRelayService   relay.CodexRelayService

	AdminRepo        repository.AdminRepository
	CodexAccountRepo repository.CodexAccountRepository
	APIKeyRepo       repository.APIKeyRepository
}

func provideGormDB(db *database.DB) *gorm.DB {
	return db.DB
}

func provideRedisClient(client *redis.Client) *redis.Client {
	return client
}

func provideOAuth2Config(cfg *config.Config) *oauth2.Config {
	scopesStr := cfg.Codex.OAuth.Scopes
	var scopes []string
	if scopesStr != "" {
		scopes = strings.Split(strings.TrimSpace(scopesStr), " ")
	}
	return &oauth2.Config{
		ClientID:     cfg.Codex.OAuth.ClientID,
		ClientSecret: cfg.Codex.OAuth.ClientSecret,
		Endpoint: oauth2.Endpoint{
			AuthURL:   cfg.Codex.OAuth.AuthURL,
			TokenURL:  cfg.Codex.OAuth.TokenURL,
			AuthStyle: oauth2.AuthStyleInParams,
		},
		Scopes: scopes,
	}
}

func provideDefaultHTTPClient() *http.Client {
	return &http.Client{Timeout: 30 * time.Second}
}

func provideSchedulerStrategy(cfg *config.Config, repo redis2.ConcurrencyRepository) (scheduler2.SelectionStrategy, error) {
	strategyType := scheduler2.StrategyType(cfg.Scheduler.Strategy)
	if strategyType == "" {
		strategyType = scheduler2.StrategyTypePriority
	}
	return scheduler2.NewStrategy(strategyType, repo)
}

func provideAccountConcurrencyRepo(client *redis.Client) redis2.ConcurrencyRepository {
	return redis2.NewAccountConcurrencyRepository(client)
}

func provideAdminService(
	adminRepo repository.AdminRepository,
	cfg *config.Config,
	log *zap.Logger,
) admin.AdminService {
	return admin.NewAdminService(
		adminRepo,
		cfg.Security.JWTSecret,
		cfg.Security.TokenExpiration,
		log,
	)
}

func provideProxyClientManager(
	proxyRepo repository.ProxyConfigRepository,
	cfg *config.Config,
	log *zap.Logger,
) proxy.ProxyClientManager {
	return proxy.NewProxyClientManager(
		proxyRepo,
		cfg.Security.EncryptionKey,
		log,
	)
}

func provideProxyConfigService(
	proxyRepo repository.ProxyConfigRepository,
	proxyClientManager proxy.ProxyClientManager,
	cfg *config.Config,
	log *zap.Logger,
) proxy.ProxyConfigService {
	return proxy.NewProxyConfigService(
		proxyRepo,
		cfg.Security.EncryptionKey,
		log,
		proxyClientManager,
	)
}

func provideCodexAccountService(
	codexAccountRepo repository.CodexAccountRepository,
	oauthStateRepo redis2.OAuthStateRepository,
	oauthConfig *oauth2.Config,
	defaultHTTPClient *http.Client,
	proxyClientManager proxy.ProxyClientManager,
	cfg *config.Config,
	log *zap.Logger,
) account.CodexAccountService {
	return account.NewCodexAccountService(
		codexAccountRepo,
		oauthStateRepo,
		cfg.Security.EncryptionKey,
		oauthConfig,
		defaultHTTPClient,
		proxyClientManager,
		log,
	)
}

func providePricingService(log *zap.Logger) billing.PricingService {
	return billing.NewPricingService("config/model_prices_and_context_window.json", log)
}

func provideSchedulerService(
	codexAccountRepo repository.CodexAccountRepository,
	sessionRepo redis2.SessionRepository,
	concurrencyRepo redis2.ConcurrencyRepository,
	healthRepo redis2.HealthRepository,
	strategy scheduler2.SelectionStrategy,
	cfg *config.Config,
	log *zap.Logger,
) scheduler.SchedulerService {
	sessionTTL := cfg.Scheduler.SessionTTL
	if sessionTTL == 0 {
		sessionTTL = 24 * time.Hour
	}
	maxAccountConcurrency := cfg.Limits.DefaultConcurrentRequests
	return scheduler.NewSchedulerService(
		codexAccountRepo,
		sessionRepo,
		concurrencyRepo,
		healthRepo,
		strategy,
		sessionTTL,
		maxAccountConcurrency,
		log,
	)
}

func provideCleanupService(
	codexAccountRepo repository.CodexAccountRepository,
	log *zap.Logger,
) scheduler.CleanupService {
	return scheduler.NewCleanupService(
		codexAccountRepo,
		log,
		5*time.Minute,
	)
}

func provideHealthChecker(
	codexAccountRepo repository.CodexAccountRepository,
	healthRepo redis2.HealthRepository,
	log *zap.Logger,
) health.HealthChecker {
	return health.NewHealthChecker(
		codexAccountRepo,
		healthRepo,
		2*time.Minute,
		log,
	)
}

func provideCodexRelayService(
	schedulerService scheduler.SchedulerService,
	codexAccountService account.CodexAccountService,
	usageCollector billing.UsageCollector,
	proxyClientManager proxy.ProxyClientManager,
	cfg *config.Config,
	log *zap.Logger,
) relay.CodexRelayService {
	return relay.NewCodexRelayService(
		schedulerService,
		codexAccountService,
		usageCollector,
		proxyClientManager,
		log,
		cfg.Logging.LogPayloads,
	)
}

var repositorySet = wire.NewSet(postgres.NewCodexAccountRepository, postgres.NewAPIKeyRepository, postgres.NewAdminRepository, postgres.NewUsageRepository, postgres.NewProxyConfigRepository, redis2.NewSessionRepository, provideAccountConcurrencyRepo, redis2.NewOAuthStateRepository, redis2.NewHealthRepository, redis2.NewRateLimitRepository)

func provideConcurrencyTracker(client *redis.Client, log *zap.Logger) limit.ConcurrencyTracker {
	apiKeyConcurrencyRepo := redis2.NewAPIKeyConcurrencyRepository(client)
	return limit.NewConcurrencyTracker(apiKeyConcurrencyRepo, log)
}

var serviceSet = wire.NewSet(
	provideAdminService,
	provideProxyClientManager,
	provideProxyConfigService,
	provideCodexAccountService,
	providePricingService, billing.NewCostCalculator, billing.NewUsageCollector, limit.NewCostLimiter, provideSchedulerService,
	provideCleanupService,
	provideHealthChecker,
	provideCodexRelayService,
	provideConcurrencyTracker, limit.NewRateLimiter, wire.Struct(new(Services), "*"),
)
